### ISSUE TITLE
New features for README.md file

### ISSUE THREAD

**Issue by miguelangellus** [PortalNetZone/librarypython#5]
Coming Soon!

**Comment by marcosranes** [comment]
Hey there!
Just a piece of advice before proceeding to that:
* create a new branch with the number of this issue (e. g. new branch = 5)
* commit and push through that along with `close #5` below the commit message
* send us a `PR` with the commit message as the title

Following these recommendations, it won't take too long for our approval.

**Comment by miguelangellus** [comment]
that's okay, there we go!
